"""``crosstable.txt``: Vega's players and their results so far.

The file as Vega 12.1.8 writes it, verbatim from the spike::

    Rochade M0 Spike
    Rochade - 05/09/2026, 07/09/2026

     Cross Table at round 2

      N NAME                 Rtg   T  Fed  Pts |   1     2
    --------------------------------------------------------
      1 Baumann, Lukas       2201  FM SUI  1.5 | +W5   =B2
      4 Mueller, Tobias      2044     SUI  2.0 | +F8   +B9
      5 Fischer, Jonas       1987     GER  0.5 | -B1   =HPB
      9 Jenni, Rafael        1755     SUI  1.0 | +PAB  -W4
     10 Keller, Simon           0     SUI  0.0 |  --    --

     Generated by Vega - www.vegachess.com

Columns are located from the header row rather than hard-coded, so a
tournament with longer names -- Vega widens the name column -- still reads.
A cell is the player's result (``+`` ``=`` ``-``), then either the colour and
the opponent's start number, ``F`` and the opponent for a forfeit (Vega drops
the colour there), or a bye: ``PAB`` pairing-allocated, ``HPB`` half point.
``--`` is a round the player was not in. UTF-8, mixed line endings.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

#: What a cross-table cell means in TRF terms, by its three-letter bye code.
BYE_CODES = {"PAB": "U", "HPB": "H", "FPB": "F", "ZPB": "Z"}

_ROUND_HEADER = re.compile(r"^\s*Cross Table at round (\d+)\s*$")
_CELL = re.compile(r"^(?P<result>[+=\-])(?P<kind>[WBF])(?P<opponent>\d+)$")
_BYE = re.compile(r"^(?P<result>[+=\-])(?P<code>[A-Z]{3})$")
_RESULT_OF = {"+": "1", "=": "=", "-": "0"}
_FORFEIT_OF = {"+": "+", "-": "-"}


class CrossTableError(ValueError):
    def __init__(self, message: str, *, line_no: int | None = None) -> None:
        super().__init__(message)
        self.line_no = line_no


@dataclass(frozen=True, slots=True)
class RoundCell:
    """One cell of the history, in TRF terms.

    ``opponent`` is None for a bye or an absence, ``colour`` is ``w``, ``b``
    or ``-`` -- the last for byes and for forfeits, whose colour Vega does not
    print. ``result`` is a TRF code; blank means the player was not in the
    round. ``raw`` is what Vega wrote, kept for the audit and for cells this
    module does not understand (``result`` is blank and ``known`` is False).
    """

    round_no: int
    raw: str
    result: str = " "
    colour: str = "-"
    opponent: int | None = None
    known: bool = True

    @property
    def is_absent(self) -> bool:
        return self.result == " " and self.known


@dataclass(frozen=True, slots=True)
class CrossTableRow:
    number: int
    name: str
    rating: int | None
    title: str
    federation: str
    points: float
    cells: tuple[RoundCell, ...]


@dataclass(frozen=True, slots=True)
class CrossTable:
    tournament_name: str
    #: The round the table is "at": the last round with results in it.
    round_no: int
    rows: tuple[CrossTableRow, ...]

    @property
    def unknown_cells(self) -> list[str]:
        return sorted({c.raw for row in self.rows for c in row.cells if not c.known})


def looks_like_cross_table(line: str) -> bool:
    return _ROUND_HEADER.match(line) is not None


def parse_cross_table(text: str) -> CrossTable:
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    round_no: int | None = None
    header_at: int | None = None
    for index, line in enumerate(lines):
        if round_no is None:
            if match := _ROUND_HEADER.match(line):
                round_no = int(match.group(1))
            continue
        if "NAME" in line and "Rtg" in line and "|" in line:
            header_at = index
            break
    if round_no is None:
        raise CrossTableError("not a Vega cross table: no 'Cross Table at round N' line")
    if header_at is None:
        raise CrossTableError("the cross table has no column header", line_no=round_no)

    header = lines[header_at]
    columns = _Columns.of(header)
    name = _name_of(lines)

    rows: list[CrossTableRow] = []
    for offset, line in enumerate(lines[header_at + 1 :], start=header_at + 2):
        if not line.strip() or set(line.strip()) == {"-"}:
            continue
        if "|" not in line:
            # "Generated by Vega" and anything after the table.
            if rows:
                break
            continue
        rows.append(_row(line, columns, line_no=offset))

    if not rows:
        raise CrossTableError("the cross table has no player rows", line_no=header_at + 1)
    return CrossTable(tournament_name=name, round_no=round_no, rows=tuple(rows))


@dataclass(frozen=True, slots=True)
class _Columns:
    rating: int
    title: int
    federation: int
    bar: int

    @classmethod
    def of(cls, header: str) -> _Columns:
        try:
            rating = header.index("Rtg")
            title = header.index(" T ", rating) + 1
            federation = header.index("Fed", title)
            bar = header.index("|")
        except ValueError as exc:
            raise CrossTableError(f"unexpected cross table header: {header.strip()!r}") from exc
        return cls(rating=rating, title=title, federation=federation, bar=bar)


def _name_of(lines: list[str]) -> str:
    for line in lines:
        if line.strip():
            return line.strip()
    return ""


def _row(line: str, columns: _Columns, *, line_no: int) -> CrossTableRow:
    bar = line.find("|")
    if bar < 0:
        raise CrossTableError("player row without a results column", line_no=line_no)
    left, right = line[:bar], line[bar + 1 :]
    # Vega's columns are right-aligned numbers and left-aligned text; the
    # header tells where each begins, and the name is whatever sits between
    # the start number and the rating.
    number_text = left.split(None, 1)[0] if left.strip() else ""
    try:
        number = int(number_text)
    except ValueError as exc:
        raise CrossTableError(
            f"expected a start number, found {number_text!r}", line_no=line_no
        ) from exc
    name = _name_from(left, columns)
    rating_text = left[columns.rating : columns.rating + 4].strip()
    title = left[columns.title - 1 : columns.title + 2].strip()
    federation = left[columns.federation : columns.federation + 3].strip()
    points_text = left[columns.federation + 3 :].strip()
    try:
        rating = int(rating_text) if rating_text else None
        points = float(points_text)
    except ValueError as exc:
        raise CrossTableError(
            f"could not read rating/points from {left.strip()!r}", line_no=line_no
        ) from exc
    if rating == 0:
        rating = None
    if not name:
        raise CrossTableError(f"player {number} has no name", line_no=line_no)
    cells = tuple(_cell(round_no, raw) for round_no, raw in enumerate(right.split(), start=1))
    return CrossTableRow(
        number=number,
        name=name,
        rating=rating,
        title=title,
        federation=federation,
        points=points,
        cells=cells,
    )


def _name_from(left: str, columns: _Columns) -> str:
    """The name field: after the start number, before the rating column."""
    head = left[: columns.rating]
    stripped = head.lstrip()
    # Skip the start number and the single space after it.
    _, _, name = stripped.partition(" ")
    return name.strip()


def _cell(round_no: int, raw: str) -> RoundCell:
    if raw == "--":
        return RoundCell(round_no=round_no, raw=raw)
    if match := _CELL.match(raw):
        result, kind, opponent = match.group("result", "kind", "opponent")
        if kind == "F":
            code = _FORFEIT_OF.get(result)
            if code is None:
                return RoundCell(round_no=round_no, raw=raw, known=False)
            return RoundCell(round_no=round_no, raw=raw, result=code, opponent=int(opponent))
        return RoundCell(
            round_no=round_no,
            raw=raw,
            result=_RESULT_OF[result],
            colour="w" if kind == "W" else "b",
            opponent=int(opponent),
        )
    if match := _BYE.match(raw):
        code = BYE_CODES.get(match.group("code"))
        if code is not None:
            return RoundCell(round_no=round_no, raw=raw, result=code)
    return RoundCell(round_no=round_no, raw=raw, known=False)
