"""``SortedPairs.txt``: the boards of the round Vega just paired, by name.

Verbatim from Vega 12.1.8::

    Rochade M0 Spike: Pairing of round 3 sorted by name

    ==========================================================================================
    BYE                   plays with black VS         Gruber, Sarah          in board    5
    Baumann, Lukas        plays with white VS         Dubois, Elise          in board    2
    Chen, Wei             plays with black VS         Mueller, Tobias        in board    1
    ...
    Mueller, Tobias       plays with white VS         Chen, Wei              in board    1

     Generated by Vega - www.vegachess.com

Every board is listed twice, once from each side; the bye is a game against
the literal ``BYE``. Names are bare -- no title -- and UTF-8. This file, unlike
``engine.man`` beside it, is rewritten when the arbiter changes a pairing by
hand, which is why it is the one Rochade reads.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

_HEADER = re.compile(r"^(?P<name>.*?):\s*Pairing of round (?P<round>\d+) sorted by name\s*$")
_LINE = re.compile(
    r"^(?P<a>.+?)\s+plays with (?P<colour>white|black) VS\s+"
    r"(?P<b>.+?)\s+in board\s+(?P<board>\d+)\s*$"
)
BYE_NAME = "BYE"
#: An unlicensed Vega prefixes the tournament name with this in every file.
_UNREGISTERED = re.compile(r"^\s*\(copy licensed to: unregistered\)\s*")


class SortedPairsError(ValueError):
    def __init__(self, message: str, *, line_no: int | None = None) -> None:
        super().__init__(message)
        self.line_no = line_no


@dataclass(frozen=True, slots=True)
class SortedPair:
    board: int
    white: str
    #: None for the pairing-allocated bye.
    black: str | None

    @property
    def is_bye(self) -> bool:
        return self.black is None


@dataclass(frozen=True, slots=True)
class SortedPairs:
    tournament_name: str
    round_no: int
    boards: tuple[SortedPair, ...]


def looks_like_sorted_pairs(line: str) -> bool:
    return _HEADER.match(line) is not None


def parse_sorted_pairs(text: str) -> SortedPairs:
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    header: re.Match[str] | None = None
    by_board: dict[int, SortedPair] = {}
    for line_no, line in enumerate(lines, start=1):
        if header is None:
            header = _HEADER.match(line.strip())
            continue
        match = _LINE.match(line.strip())
        if match is None:
            continue
        a, colour, b, board = match.group("a", "colour", "b", "board")
        if a == BYE_NAME:
            # The bye's own line; the player's line carries the same board.
            continue
        white, black = (a, b) if colour == "white" else (b, a)
        if black == BYE_NAME:
            pair = SortedPair(board=int(board), white=a, black=None)
        elif white == BYE_NAME:
            raise SortedPairsError(f"board {board}: the bye plays white", line_no=line_no)
        else:
            pair = SortedPair(board=int(board), white=white, black=black)
        held = by_board.get(pair.board)
        if held is not None and held != pair:
            raise SortedPairsError(
                f"board {board} is listed twice with different players", line_no=line_no
            )
        by_board[pair.board] = pair
    if header is None:
        raise SortedPairsError(
            "not a Vega pairing list: no 'Pairing of round N sorted by name' line"
        )
    if not by_board:
        raise SortedPairsError("the pairing list has no boards")
    return SortedPairs(
        tournament_name=_UNREGISTERED.sub("", header.group("name")).strip(),
        round_no=int(header.group("round")),
        boards=tuple(by_board[b] for b in sorted(by_board)),
    )
