"""The vendored engine is upstream's code, byte for byte.

Lint and type checks skip the vendor directory, so nothing else would notice
a stray edit to `pairingdutch.py`. The digest file beside `VENDOR.md` is
regenerated by the refresh procedure it describes; a mismatch here means
either the snapshot moved without the note, or something was changed by hand.
"""

from __future__ import annotations

import hashlib
import pathlib

from rochade.gacrux.engine import PACKAGED_ENGINE

DIGESTS = PACKAGED_ENGINE / "VENDOR.sha256"


def _digest_lines() -> dict[str, str]:
    return {
        name: digest
        for digest, name in (
            line.split("  ", 1) for line in DIGESTS.read_text(encoding="utf-8").splitlines() if line
        )
    }


def _actual() -> dict[str, str]:
    return {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(PACKAGED_ENGINE.glob("*.py"))
    }


def test_every_vendored_module_matches_its_recorded_digest() -> None:
    recorded = _digest_lines()
    actual = _actual()
    assert set(actual) == set(recorded), "modules were added or removed without VENDOR.sha256"
    changed = sorted(name for name, digest in actual.items() if recorded[name] != digest)
    assert changed == [], f"vendored files differ from the recorded snapshot: {changed}"


def test_the_licence_travels_with_the_snapshot() -> None:
    licence = (PACKAGED_ENGINE / "LICENSE").read_text(encoding="utf-8")
    assert "Copyright (c) 2024 FIDE" in licence
    assert (pathlib.Path(__file__).resolve().parents[2] / "NOTICE").is_file()
