"""baseline schema

Revision ID: 08baadaf4d87
Revises:
Create Date: 2026-09-01 01:15:45.299355
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "08baadaf4d87"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_record",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("command", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tournament",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("federation", sa.String(length=8), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "device",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournament.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_token_hash"), "device", ["token_hash"], unique=True)
    op.create_index(op.f("ix_device_tournament_id"), "device", ["tournament_id"], unique=False)
    op.create_table(
        "section",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("declared_rounds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournament.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tournament_id", "name", name="uq_section_name"),
    )
    op.create_index(op.f("ix_section_tournament_id"), "section", ["tournament_id"], unique=False)
    op.create_table(
        "tournament_member",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ARBITER", "ASSISTANT", name="role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournament.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tournament_id", "subject", name="uq_member_subject"),
    )
    op.create_index(
        op.f("ix_tournament_member_tournament_id"),
        "tournament_member",
        ["tournament_id"],
        unique=False,
    )
    op.create_table(
        "game_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("white_name", sa.String(length=120), nullable=True),
        sa.Column("black_name", sa.String(length=120), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "ROUND_IMPORTED",
                "RESULT_CLAIMED",
                "RESULT_DISPUTED",
                "RESULT_SET",
                "DISPUTE_RESOLVED",
                "ROUND_RELEASED",
                "ROUND_EXPORTED",
                "CLAIM_DROPPED",
                "DEVICE_ISSUED",
                "DEVICE_REVOKED",
                name="event_action",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "actor_kind",
            sa.Enum(
                "STAFF", "DEVICE", "SYSTEM", name="principal_kind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("actor_subject", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_event_created", "game_event", ["created_at"], unique=False)
    op.create_index("ix_event_natural", "game_event", ["section_id", "round_number"], unique=False)
    op.create_index(op.f("ix_game_event_section_id"), "game_event", ["section_id"], unique=False)
    op.create_table(
        "round",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "OPEN", "CONFIRMED", "EXPORTED", name="round_state", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("source_trf", sa.Text(), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "number", name="uq_round_number"),
    )
    op.create_index(op.f("ix_round_section_id"), "round", ["section_id"], unique=False)
    op.create_table(
        "section_player",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("start_rank", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=8), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("federation", sa.String(length=8), nullable=False),
        sa.Column("fide_id", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "start_rank", name="uq_player_rank"),
    )
    op.create_index(
        op.f("ix_section_player_section_id"), "section_player", ["section_id"], unique=False
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("board", sa.Integer(), nullable=False),
        sa.Column("white_rank", sa.Integer(), nullable=False),
        sa.Column("white_name", sa.String(length=120), nullable=False),
        sa.Column("black_rank", sa.Integer(), nullable=True),
        sa.Column("black_name", sa.String(length=120), nullable=True),
        sa.Column("white_result", sa.String(length=1), nullable=False),
        sa.Column("black_result", sa.String(length=1), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "EMPTY",
                "CLAIMED",
                "DISPUTED",
                "CONFIRMED",
                name="result_state",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("disputed_white_result", sa.String(length=1), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'confirmed' OR white_result <> ' '", name="ck_game_confirmed_has_result"
        ),
        sa.CheckConstraint(
            "state <> 'empty' OR white_result = ' '", name="ck_game_empty_has_no_result"
        ),
        sa.CheckConstraint(
            "(black_rank IS NULL) = (black_name IS NULL)", name="ck_game_black_consistent"
        ),
        sa.CheckConstraint("board > 0", name="ck_game_board_positive"),
        sa.ForeignKeyConstraint(["round_id"], ["round.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_id", "board", name="uq_game_board"),
    )
    op.create_index(op.f("ix_game_round_id"), "game", ["round_id"], unique=False)
    op.create_index("ix_game_round_state", "game", ["round_id", "state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_game_round_state", table_name="game")
    op.drop_index(op.f("ix_game_round_id"), table_name="game")
    op.drop_table("game")
    op.drop_index(op.f("ix_section_player_section_id"), table_name="section_player")
    op.drop_table("section_player")
    op.drop_index(op.f("ix_round_section_id"), table_name="round")
    op.drop_table("round")
    op.drop_index(op.f("ix_game_event_section_id"), table_name="game_event")
    op.drop_index("ix_event_natural", table_name="game_event")
    op.drop_index("ix_event_created", table_name="game_event")
    op.drop_table("game_event")
    op.drop_index(op.f("ix_tournament_member_tournament_id"), table_name="tournament_member")
    op.drop_table("tournament_member")
    op.drop_index(op.f("ix_section_tournament_id"), table_name="section")
    op.drop_table("section")
    op.drop_index(op.f("ix_device_tournament_id"), table_name="device")
    op.drop_index(op.f("ix_device_token_hash"), table_name="device")
    op.drop_table("device")
    op.drop_table("tournament")
    op.drop_table("idempotency_record")
    # ### end Alembic commands ###
