"""section carries its manager adapter

Revision ID: e89c5e8380ff
Revises: 08baadaf4d87
Create Date: 2026-09-01 22:42:13.311058
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e89c5e8380ff"
down_revision: str | None = "08baadaf4d87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "section", sa.Column("manager", sa.String(length=32), server_default="vega", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("section", "manager")
    # ### end Alembic commands ###
