/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managers */
        get: operations["list_managers_api_managers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tournaments */
        get: operations["list_tournaments_api_tournaments_get"];
        put?: never;
        /** Create Tournament */
        post: operations["create_tournament_api_tournaments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tournament */
        get: operations["get_tournament_api_tournaments__tournament_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_api_tournaments__tournament_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Import */
        post: operations["preview_import_api_tournaments__tournament_id__imports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Round */
        post: operations["import_round_api_tournaments__tournament_id__imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board List */
        get: operations["get_board_list_api_tournaments__tournament_id__boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Arbiter Queue */
        get: operations["get_arbiter_queue_api_tournaments__tournament_id__queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_tournaments__tournament_id__devices_get"];
        put?: never;
        /** Issue Device Token */
        post: operations["issue_device_token_api_tournaments__tournament_id__devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Device */
        delete: operations["remove_device_api_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Device */
        post: operations["revoke_device_api_devices__device_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings */
        get: operations["get_standings_api_tournaments__tournament_id__standings_get"];
        put?: never;
        /** Import Standings */
        post: operations["import_standings_api_tournaments__tournament_id__standings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/sections/{section_name}/tiebreaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Name Tiebreaks */
        put: operations["name_tiebreaks_api_tournaments__tournament_id__sections__section_name__tiebreaks_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/join-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Join Code */
        post: operations["set_join_code_api_tournaments__tournament_id__join_code_post"];
        /** Clear Join Code */
        delete: operations["clear_join_code_api_tournaments__tournament_id__join_code_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Device */
        post: operations["join_device_api_devices_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round */
        get: operations["get_round_api_rounds__round_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round Events */
        get: operations["get_round_events_api_rounds__round_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Boards */
        post: operations["confirm_boards_api_rounds__round_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Round */
        post: operations["release_round_api_rounds__round_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export File */
        get: operations["get_export_file_api_rounds__round_id__export_get"];
        put?: never;
        /** Export Round */
        post: operations["export_round_api_rounds__round_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Result */
        post: operations["claim_result_api_games__game_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Result */
        put: operations["set_result_api_games__game_id__result_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Dispute */
        post: operations["resolve_dispute_api_games__game_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddMember */
        AddMember: {
            /**
             * Tournament Id
             * Format: uuid
             */
            tournament_id: string;
            /** Subject */
            subject: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** @default arbiter */
            role: components["schemas"]["Role"];
        };
        /** ArbiterQueue */
        ArbiterQueue: {
            /**
             * Tournament Id
             * Format: uuid
             */
            tournament_id: string;
            /**
             * Disputed
             * @default 0
             */
            disputed: number;
            /**
             * Empty
             * @default 0
             */
            empty: number;
            /**
             * Claimed
             * @default 0
             */
            claimed: number;
            /**
             * Confirmed
             * @default 0
             */
            confirmed: number;
            /** Entries */
            entries?: components["schemas"]["QueueEntry"][];
        };
        /** BoardDetail */
        BoardDetail: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /** Board */
            board: number;
            /** White Rank */
            white_rank: number;
            /** White Name */
            white_name: string;
            /** Black Rank */
            black_rank: number | null;
            /** Black Name */
            black_name: string | null;
            /** White Result */
            white_result: string;
            /** Black Result */
            black_result: string;
            /** Disputed White Result */
            disputed_white_result: string | null;
            state: components["schemas"]["ResultState"];
            /** Is Bye */
            is_bye: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CarriedClaim */
        CarriedClaim: {
            /** White Name */
            white_name: string;
            /** Black Name */
            black_name: string | null;
            /** White Result */
            white_result: string;
            state: components["schemas"]["ResultState"];
        };
        /** ClaimBody */
        ClaimBody: {
            result: components["schemas"]["GameResult"];
        };
        /** ClaimResultResult */
        ClaimResultResult: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            state: components["schemas"]["ResultState"];
            /** White Result */
            white_result: string;
            /** Black Result */
            black_result: string;
            /** Disputed */
            disputed: boolean;
        };
        /** ConfirmBoardsResult */
        ConfirmBoardsResult: {
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /** Confirmed */
            confirmed: number;
            /** Skipped */
            skipped?: number[];
        };
        /** ConfirmBody */
        ConfirmBody: {
            /** Game Ids */
            game_ids?: string[];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** CreateTournament */
        CreateTournament: {
            /** Name */
            name: string;
            /**
             * City
             * @default
             */
            city: string;
            /**
             * Federation
             * @default
             */
            federation: string;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** CreateTournamentResult */
        CreateTournamentResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** DeviceSummary */
        DeviceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Active */
            active: boolean;
        };
        /**
         * EventAction
         * @description Every entry in the append-only audit log.
         * @enum {string}
         */
        EventAction: "round_imported" | "result_claimed" | "result_corrected" | "result_disputed" | "result_set" | "result_confirmed" | "dispute_resolved" | "round_released" | "round_exported" | "claim_dropped" | "device_issued" | "device_revoked" | "device_removed" | "standings_imported";
        /** ExportBody */
        ExportBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** ExportRoundResult */
        ExportRoundResult: {
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /** Round Number */
            round_number: number;
            /** Filename */
            filename: string;
            /** Content */
            content: string;
            /** Manager */
            manager: string;
            /** Manager Label */
            manager_label: string;
            /** File Format */
            file_format: string;
            /** Next Step */
            next_step: string;
            /** Boards Written */
            boards_written: number;
            /** Boards Left Blank */
            boards_left_blank?: number[];
            /** Forced */
            forced: boolean;
        };
        /**
         * GameResult
         * @description The three outcomes a player may enter at the board.
         *
         *     Deliberately not the same set as the TRF codes: forfeits and byes are
         *     arbiter business, and a phone in the hall must not be able to record one.
         * @enum {string}
         */
        GameResult: "white_win" | "draw" | "black_win";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallBoard */
        HallBoard: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Section Id
             * Format: uuid
             */
            section_id: string;
            /** Section Name */
            section_name: string;
            /** Round Number */
            round_number: number;
            /** Board */
            board: number;
            /** White Name */
            white_name: string;
            /** Black Name */
            black_name: string | null;
            /** White Result */
            white_result: string;
            state: components["schemas"]["ResultState"];
            /** Is Bye */
            is_bye: boolean;
            /** Entered */
            entered: boolean;
        };
        /** HallBoardList */
        HallBoardList: {
            /**
             * Tournament Id
             * Format: uuid
             */
            tournament_id: string;
            /** Tournament Name */
            tournament_name: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Open Rounds */
            open_rounds?: number[];
            /** Boards */
            boards?: components["schemas"]["HallBoard"][];
        };
        /** ImportPlan */
        ImportPlan: {
            /** Section Name */
            section_name: string;
            /** Section Exists */
            section_exists: boolean;
            /** File Round */
            file_round: number;
            /** Expected Round */
            expected_round: number;
            /** Is Expected Round */
            is_expected_round: boolean;
            /** Declared Rounds */
            declared_rounds: number | null;
            /** Tournament Name */
            tournament_name: string;
            /** Players Total */
            players_total: number;
            /** Players Added */
            players_added?: components["schemas"]["PlayerChange"][];
            /** Players Removed */
            players_removed?: components["schemas"]["PlayerChange"][];
            /** Players Renamed */
            players_renamed?: string[];
            /** Boards */
            boards: number;
            /** Byes */
            byes: number;
            /** Disagreements */
            disagreements?: components["schemas"]["ResultDisagreement"][];
            /** Claims Carried */
            claims_carried?: components["schemas"]["CarriedClaim"][];
            /** Claims Dropped */
            claims_dropped?: components["schemas"]["CarriedClaim"][];
            /** Unknown Result Codes */
            unknown_result_codes?: string[];
            /** Warnings */
            warnings?: string[];
            /** Blocked By */
            blocked_by?: string[];
        };
        /** ImportRoundBody */
        ImportRoundBody: {
            /** Section Name */
            section_name: string;
            /** Content */
            content: string;
            /**
             * Filename
             * @default
             */
            filename: string;
            /**
             * Manager
             * @default vega
             */
            manager: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** ImportRoundResult */
        ImportRoundResult: {
            /**
             * Section Id
             * Format: uuid
             */
            section_id: string;
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /** Round Number */
            round_number: number;
            /** Boards */
            boards: number;
            /** Byes */
            byes: number;
            /** Claims Carried */
            claims_carried: number;
            /** Claims Dropped */
            claims_dropped: number;
        };
        /** ImportStandingsBody */
        ImportStandingsBody: {
            /** Section Name */
            section_name: string;
            /** Content */
            content: string;
        };
        /** ImportStandingsResult */
        ImportStandingsResult: {
            /** Section Name */
            section_name: string;
            /** After Round */
            after_round: number;
            /** Players Updated */
            players_updated: number;
            /** Unknown Start Numbers */
            unknown_start_numbers?: number[];
            standings: components["schemas"]["SectionStandings"];
        };
        /** IssueDeviceBody */
        IssueDeviceBody: {
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Base Url
             * @default
             */
            base_url: string;
        };
        /** IssueDeviceTokenResult */
        IssueDeviceTokenResult: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Label */
            label: string;
            /** Token */
            token: string;
            /** Qr Payload */
            qr_payload: string;
        };
        /** JoinBody */
        JoinBody: {
            /** Code */
            code: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** JoinCodeResult */
        JoinCodeResult: {
            /** Join Code */
            join_code: string | null;
        };
        /** JoinedDevice */
        JoinedDevice: {
            /**
             * Tournament Id
             * Format: uuid
             */
            tournament_id: string;
            /** Tournament Name */
            tournament_name: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Label */
            label: string;
            /** Token */
            token: string;
        };
        /** ManagerSummary */
        ManagerSummary: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Reads Format */
            reads_format: string;
            /** Writes Format */
            writes_format: string;
            exports_unplayed_round: components["schemas"]["Support"];
            merges_on_import: components["schemas"]["Support"];
            /** Verified */
            verified: boolean;
            /** Result Codes Out */
            result_codes_out?: string[];
            /**
             * Export Howto
             * @default
             */
            export_howto: string;
            /**
             * Import Howto
             * @default
             */
            import_howto: string;
            /** Notes */
            notes?: string[];
        };
        /** MemberResult */
        MemberResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject */
            subject: string;
            role: components["schemas"]["Role"];
        };
        /** PlayerChange */
        PlayerChange: {
            /** Start Rank */
            start_rank: number;
            /** Name */
            name: string;
            /** Rating */
            rating?: number | null;
        };
        /** PreviewBody */
        PreviewBody: {
            /** Section Name */
            section_name: string;
            /** Content */
            content: string;
            /**
             * Manager
             * @default vega
             */
            manager: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * PrincipalKind
         * @enum {string}
         */
        PrincipalKind: "staff" | "device" | "system" | "anonymous";
        /** QueueEntry */
        QueueEntry: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /** Section Name */
            section_name: string;
            /** Round Number */
            round_number: number;
            /** Board */
            board: number;
            /** White Name */
            white_name: string;
            /** Black Name */
            black_name: string | null;
            /** White Result */
            white_result: string;
            /** Disputed White Result */
            disputed_white_result: string | null;
            state: components["schemas"]["ResultState"];
            /** Is Bye */
            is_bye: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReleaseBody */
        ReleaseBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ReleaseRoundResult */
        ReleaseRoundResult: {
            /**
             * Round Id
             * Format: uuid
             */
            round_id: string;
            /** Round Number */
            round_number: number;
            state: components["schemas"]["RoundState"];
            /** Confirmed */
            confirmed: number;
            /** Forced */
            forced: boolean;
        };
        /** RemoveDeviceResult */
        RemoveDeviceResult: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
        };
        /** ResolveBody */
        ResolveBody: {
            result: components["schemas"]["GameResult"];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ResolveDisputeResult */
        ResolveDisputeResult: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            state: components["schemas"]["ResultState"];
            /** White Result */
            white_result: string;
            /** Black Result */
            black_result: string;
        };
        /**
         * ResultDisagreement
         * @description A prior-round result in the file differs from the one we hold.
         *
         *     Expected, not an error: an arbiter correcting an earlier round in Vega is
         *     normal and Vega is authoritative. It must be listed and acknowledged, never
         *     applied silently.
         */
        ResultDisagreement: {
            /** Round Number */
            round_number: number;
            /** White Name */
            white_name: string;
            /** Black Name */
            black_name: string | null;
            /** Ours */
            ours: string;
            /** Theirs */
            theirs: string;
        };
        /**
         * ResultState
         * @description Trust level of one game's result.
         * @enum {string}
         */
        ResultState: "empty" | "claimed" | "disputed" | "confirmed";
        /** RevokeDeviceResult */
        RevokeDeviceResult: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /**
             * Revoked At
             * Format: date-time
             */
            revoked_at: string;
        };
        /**
         * Role
         * @description Per-tournament staff role, resolved from `tournament_member`.
         * @enum {string}
         */
        Role: "owner" | "arbiter" | "assistant";
        /** RoundDetail */
        RoundDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            state: components["schemas"]["RoundState"];
            /**
             * Section Id
             * Format: uuid
             */
            section_id: string;
            /** Section Name */
            section_name: string;
            /** Source Filename */
            source_filename: string;
            /** Imported At */
            imported_at: string | null;
            /** Released At */
            released_at: string | null;
            /** Exported At */
            exported_at: string | null;
            /** Boards */
            boards: components["schemas"]["BoardDetail"][];
        };
        /** RoundEvent */
        RoundEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Board */
            board: number | null;
            /** White Name */
            white_name: string | null;
            /** Black Name */
            black_name: string | null;
            action: components["schemas"]["EventAction"];
            actor_kind: components["schemas"]["PrincipalKind"];
            /** Device Label */
            device_label: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * RoundState
         * @description Where a round sits in the Vega round-trip.
         *
         *     OPEN     pairings imported, players may claim results
         *     CONFIRMED the arbiter has released it; results are final
         *     EXPORTED  written back to Vega and frozen -- read-only from here on
         * @enum {string}
         */
        RoundState: "open" | "confirmed" | "exported";
        /** RoundSummary */
        RoundSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            state: components["schemas"]["RoundState"];
            /** Boards */
            boards: number;
            /** Byes */
            byes: number;
            /** Empty */
            empty: number;
            /** Claimed */
            claimed: number;
            /** Disputed */
            disputed: number;
            /** Confirmed */
            confirmed: number;
            /** Imported At */
            imported_at: string | null;
            /** Released At */
            released_at: string | null;
            /** Exported At */
            exported_at: string | null;
        };
        /** SectionStandings */
        SectionStandings: {
            /**
             * Section Id
             * Format: uuid
             */
            section_id: string;
            /** Section Name */
            section_name: string;
            /** Manager Label */
            manager_label: string;
            /** After Round */
            after_round: number;
            /** Rounds Held */
            rounds_held: number;
            /** Stale */
            stale: boolean;
            /** Tiebreak Names */
            tiebreak_names: string[];
            /** Tiebreak Columns */
            tiebreak_columns: number;
            /** Rows */
            rows: components["schemas"]["StandingRow"][];
        };
        /** SectionSummary */
        SectionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Manager */
            manager: string;
            /** Manager Label */
            manager_label: string;
            /** Players */
            players: number;
            /** Declared Rounds */
            declared_rounds: number | null;
            /** Rounds */
            rounds: components["schemas"]["RoundSummary"][];
        };
        /** SetResultBody */
        SetResultBody: {
            /** White Result */
            white_result: string;
            /**
             * Black Result
             * @default
             */
            black_result: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** SetResultResult */
        SetResultResult: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            state: components["schemas"]["ResultState"];
            /** White Result */
            white_result: string;
            /** Black Result */
            black_result: string;
        };
        /** StandingRow */
        StandingRow: {
            /** Rank */
            rank: number;
            /** Start Rank */
            start_rank: number;
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Federation */
            federation: string;
            /** Rating */
            rating: number | null;
            /** Points */
            points: number;
            /** Tiebreaks */
            tiebreaks: (number | null)[];
        };
        /**
         * Support
         * @description Whether a behaviour has actually been observed against the real program.
         *
         *     UNVERIFIED is the honest default and the whole point of the enum: until the
         *     M0 spike is run against a program, we are repeating documentation rather
         *     than reporting a fact, and an arbiter deserves to be told which it is.
         * @enum {string}
         */
        Support: "yes" | "no" | "unverified";
        /** TiebreakNamesBody */
        TiebreakNamesBody: {
            /** Names */
            names?: string[];
        };
        /** TiebreakNamesResult */
        TiebreakNamesResult: {
            /** Section Name */
            section_name: string;
            /** Tiebreak Names */
            tiebreak_names: string[];
        };
        /** TournamentDetail */
        TournamentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Federation */
            federation: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Join Code */
            join_code?: string | null;
            /** Sections */
            sections: components["schemas"]["SectionSummary"][];
        };
        /** TournamentStandings */
        TournamentStandings: {
            /**
             * Tournament Id
             * Format: uuid
             */
            tournament_id: string;
            /** Tournament Name */
            tournament_name: string;
            /** Sections */
            sections?: components["schemas"]["SectionStandings"][];
        };
        /** TournamentSummary */
        TournamentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            role: components["schemas"]["Role"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_managers_api_managers_get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tournaments_api_tournaments_get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tournament_api_tournaments_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTournament"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTournamentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tournament_api_tournaments__tournament_id__get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_tournaments__tournament_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMember"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_import_api_tournaments__tournament_id__imports_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_round_api_tournaments__tournament_id__imports_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRoundBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRoundResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_list_api_tournaments__tournament_id__boards_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallBoardList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_arbiter_queue_api_tournaments__tournament_id__queue_get: {
        parameters: {
            query?: {
                include_confirmed?: boolean;
            };
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbiterQueue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_tournaments__tournament_id__devices_get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_device_token_api_tournaments__tournament_id__devices_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueDeviceBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDeviceTokenResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_device_api_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveDeviceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_device_api_devices__device_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeDeviceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_api_tournaments__tournament_id__standings_get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentStandings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_standings_api_tournaments__tournament_id__standings_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportStandingsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStandingsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    name_tiebreaks_api_tournaments__tournament_id__sections__section_name__tiebreaks_put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
                section_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TiebreakNamesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiebreakNamesResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_join_code_api_tournaments__tournament_id__join_code_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinCodeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_join_code_api_tournaments__tournament_id__join_code_delete: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinCodeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_device_api_devices_join_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinedDevice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_api_rounds__round_id__get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_events_api_rounds__round_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_boards_api_rounds__round_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmBoardsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_round_api_rounds__round_id__release_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseRoundResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_file_api_rounds__round_id__export_get: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRoundResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_round_api_rounds__round_id__export_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRoundResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_result_api_games__game_id__claim_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResultResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_result_api_games__game_id__result_put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetResultBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetResultResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_dispute_api_games__game_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveDisputeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
